// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnmyuaoukoywuvvcnuur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFubXl1YW91a295d3V2dmNudXVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MzkzOTAsImV4cCI6MjA2NTQxNTM5MH0.RKK9O3GHxkDtKzEqHut6Zyk-urNP-WBR5n0sctCybwA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);